repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
    - id: black
      name: Black
      entry: black --check .
      language: system
      pass_filenames: false
    - id: isort
      name: Isort
      entry: isort --check --diff .
      language: system
      pass_filenames: false
    - id: flake8
      name: Flake8
      entry: flake8 .
      language: system
      pass_filenames: false
    - id: mypy
      name: Mypy
      entry: mypy .
      language: system
      pass_filenames: false
